[package]
name = "simd-minimizers-c"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
libc = "0.2"
simd-minimizers = { git = "https://github.com/rust-seq/simd-minimizers.git" }
packed-seq = "4.4.1"

[build-dependencies]
cbindgen = "0.29.2"
